#!/bin/sh
# Path to the commit message file
COMMIT_MSG_FILE=$1
# Reading the commit message
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

echo "Checking commit message format"

# Checking if the commit message contains '[skip ci]'
if echo "$COMMIT_MSG" | grep -q "\[skip ci\]"; then
  echo "Skipping commit message linting due to [skip ci]"
else
  # Running commitlint
  pnpm commitlint --edit "$COMMIT_MSG_FILE"
fi
